### PR TITLE
Pass image width information to the template

### PR DESCRIPTION
**Pull request by ranitham**
Provide template with various image widths for responsive images

### CODE REVIEW

**Comment by artifex404** [comment]
Could you please rename the `_w` to `_width` for a better readability?

**Comment by ranitham** [comment]
Done.

**Comment by artifex404** [comment]
Great! Thanks for the pull request!

**Comment by artifex404** [comment]
Re-openning to merge.

**Comment by Sogl** [comment]
@artifex404 Please release a new version with this change.

**Comment by artifex404** [comment]
Done.

**Pull request merged**
